name: "Security — Weekly Scan"

on:
  schedule:
    - cron: '0 7 * * 1'
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  tfsec-sarif:
    name: "tfsec SARIF scan"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Run tfsec with SARIF output
        uses: aquasecurity/tfsec-action@b466648d6e39e7c75324f25d83891162a721f2d6
        with:
          sarif_file: tfsec.sarif
          soft_fail: true

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@820e3160e279568db735cee8ed8f8e77a6da7818
        with:
          sarif_file: tfsec.sarif
        if: always()

  checkov:
    name: "Checkov compliance scan"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Run checkov
        uses: bridgecrewio/checkov-action@f9b0a2206b0401cad02ac0a66be2a7934a5be838
        with:
          directory: .
          framework: terraform
          soft_fail: true
          output_format: cli,sarif
          output_file_path: console,checkov.sarif

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@820e3160e279568db735cee8ed8f8e77a6da7818
        with:
          sarif_file: checkov.sarif
        if: always()
